# This workflow will do a clean install of node dependencies, build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_call:

env:
  YARN_CHECKSUM_BEHAVIOR: ignore
  PUPPETEER_SKIP_DOWNLOAD: true  # Skip downloading Chrome

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run start date
      run: echo "Started at $(date +'%Y-%m-%dT%H:%M:%S')"

    - uses: actions/checkout@v4

    # Java required for OpenAPI client generation
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        java-package: jre

    - run: corepack enable

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14'
        cache: 'yarn'

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.11'
    #     cache: 'pip'

    # - name: Install Python dependencies
    #   working-directory: ./apps/vqa-service
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Install build dependencies
    #   run: |
    #     sudo apt-get update &&
    #     sudo apt-get install -y libudev-dev libusb-1.0-0-dev libusb-dev

    - name: Configure Git and NPM
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
        echo "@thecointech:registry=https://npm.pkg.github.com" >> ~/.npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test commit & push
      run: |
        date > build-date.txt
        git add .
        git commit -m "chore: build artifacts"
        git push origin HEAD:${{ github.ref }}

    # - name: Install dependencies
    #   run: yarn install --immutable --mode=skip-build

    # - name: Build
    #   env:
    #      # Fix OOM in build admin
    #     NODE_OPTIONS: "--max-old-space-size=6144"
    #   run: yarn build

    # # Upload build artifacts for test and docker jobs
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-artifacts
    #     path: |
    #       .yarn/cache
    #       .yarn/install-state.gz
    #       apps/**/translations/*.json
    #       apps/*/build/
    #       libs/*/build/
    #       apis/**/dist/
    #       libs/contract-*/src/codegen/**
    #       package.json
    #       .yarnrc.yml
    #       yarn.lock
    #       environments/
    #       apps/tx-processor/docker/
    #     retention-days: 1

    # - name: Build Completed
    #   run: echo "Build completed at $(date +'%Y-%m-%dT%H:%M:%S')"
