name: Publish NPM Packages

on:
  workflow_call:

env:
  YARN_CHECKSUM_BEHAVIOR: ignore
  PUPPETEER_SKIP_DOWNLOAD: true  # Skip downloading Chrome

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For git operations and version bumps
      packages: write  # For package publishing
    outputs:
      latest_sha: ${{ steps.get_sha.outputs.sha }}

    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for correct versioning
          ref: ${{ github.head_ref }}

      - run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thecointech'

      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-artifacts

      # This will be fast, using the cached dependencies
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn re:build

      - name: Configure Git and NPM
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          echo "@thecointech:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Version and publish
      - name: Version and Publish
        run: yarn lerna publish --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      # Merge changes back to dev
      # - name: Merge to dev
      #   run: |
      #     git checkout dev
      #     git merge ${{ github.ref_name }} -m "chore: merge ${{ github.ref_name }} changes to dev"
      #     git push origin dev