name: Deploy to Google App Engine

on:
  workflow_call:
    inputs:
      GCP_RATES_PROJECT_ID:
        required: true
        type: string
        description: 'GCP project ID for rates service'
      GCP_BROKER_PROJECT_ID:
        required: true
        type: string
        description: 'GCP project ID for broker service'
      CONFIG_NAME:
        required: true
        type: string
        description: 'Environment to deploy to (e.g., prodtest, prod)'
      COMMIT_SHA:
        required: true
        type: string
        description: 'Commit SHA to build from'

# Already tested in build step
env:
  YARN_ENABLE_HARDENED_MODE: 0

jobs:
  deploy-rates:
    runs-on: ubuntu-latest
    environment: ${{ inputs.CONFIG_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.COMMIT_SHA }}

      - run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Generate env file
        run: yarn run-env ./deploy.ts
        env:
          CONFIG_NAME: ${{ inputs.CONFIG_NAME }}
          GithubPackageToken: ${{ secrets.GH_PACKAGES_READ }}
        working-directory: ./apps/rates-service

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_RATES_KEY }}

      - id: deploy-rates
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ env.GCP_RATES_PROJECT_ID }}
          working_directory: ./apps/rates-service

  deploy-broker:
    runs-on: ubuntu-latest
    environment: ${{ inputs.CONFIG_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.COMMIT_SHA }}

      - run: corepack enable

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Generate env file
        run: yarn run-env ./deploy.ts
        env:
          CONFIG_NAME: ${{ inputs.CONFIG_NAME }}
          GithubPackageToken: ${{ secrets.GH_PACKAGES_READ }}
        working-directory: ./apps/broker-service

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_BROKER_KEY }}

      - id: deploy-broker
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ env.GCP_BROKER_PROJECT_ID }}
          working_directory: ./apps/broker-service
